version: '3.4'

services:
  react-app:
    ports:
        - "80:80"
    image: ${DOCKER_REGISTRY-}reactapp
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "krynkszta.X"
        ACCEPT_EULA: "Y"
