version: '3.4'

services:
  react-app:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development #uncomment for docker-compose-up windows VS debugging
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro