version: '3.4'

services:
  react-app:
    ports:
        - "80:80"
    image: ${DOCKER_REGISTRY-}reactapp
    build:
      context: .
      dockerfile: Dockerfile
  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - ./DockerVolumes/sql-server-volume:/home/sql-server-volume
    environment:
        SA_PASSWORD: "krynkszta.X"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"

