version: '3.4'

services:
  sql-server:
    container_name: sql-server
    ports:
        - "14330:1433"
    image: ${DOCKER_REGISTRY-}sqlserver
    volumes:
      - ./Docker/volumes/sql-server-volume:/home/sql-server-volume
    build:
      context: .
      dockerfile: SqlServerDockerfile
  react-app:
    container_name: projack
    ports:
        - "80:80"
    image: ${DOCKER_REGISTRY-}projack
    volumes:
      - ./Docker/volumes/sql-server-volume:/home/sql-server-volume
    build:
      context: .
      dockerfile: ReactAppDockerfile